### ISSUE TITLE
Migaku Import Problem

### ISSUE THREAD

**Issue by Jakim287** [Sighmir/migaku-wr-dict#1]
Hello,

I generated a dictionary successfully but when I try to import it into Migaku I receive the following error:

```Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.35 (84dcaa86) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
Platform: Mac 10.16
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2021-06-24 11:27:52
Add-ons possibly involved: ⁨Migaku Dictionary⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/Tim/Library/Application Support/Anki2/addons21/1655992655/dictionaryManager.py", line 374, in import_dict
    importDict(lang_name, path, dict_name)
  File "/Users/Tim/Library/Application Support/Anki2/addons21/1655992655/dictionaryManager.py", line 491, in importDict
    loadDict(zfile, dict_files, lang_name, dict_name, frequency_dict, not is_yomichan)
  File "/Users/Tim/Library/Application Support/Anki2/addons21/1655992655/dictionaryManager.py", line 508, in loadDict
    jsonDict = organizeDictionaryByFrequency(jsonDict, frequencyDict, dictName, lang, True)
  File "/Users/Tim/Library/Application Support/Anki2/addons21/1655992655/dictionaryManager.py", line 595, in organizeDictionaryByFrequency
    if not readingHyouki and entry['term'] in frequencyDict:
KeyError: 'term'
```   

I've tried it with one of the example generated dictionaries and also receive an error.

```Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.35 (84dcaa86) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
Platform: Mac 10.16
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2021-06-24 11:27:52
Add-ons possibly involved: ⁨Migaku Dictionary⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/Tim/Library/Application Support/Anki2/addons21/1655992655/dictionaryManager.py", line 374, in import_dict
    importDict(lang_name, path, dict_name)
  File "/Users/Tim/Library/Application Support/Anki2/addons21/1655992655/dictionaryManager.py", line 491, in importDict
    loadDict(zfile, dict_files, lang_name, dict_name, frequency_dict, not is_yomichan)
  File "/Users/Tim/Library/Application Support/Anki2/addons21/1655992655/dictionaryManager.py", line 508, in loadDict
    jsonDict = organizeDictionaryByFrequency(jsonDict, frequencyDict, dictName, lang, True)
  File "/Users/Tim/Library/Application Support/Anki2/addons21/1655992655/dictionaryManager.py", line 595, in organizeDictionaryByFrequency
    if not readingHyouki and entry['term'] in frequencyDict:
TypeError: string indices must be integers
```

I tried to manually place the unzipped files in their respective location but the file structure that's mentioned in the instructions is not the same. I noticed that when you use the Migaku dictionary import it creates a sqlite file where it puts the dictionaries in.

Further assistance required.

**Comment by guicaulada** [comment]
Hello @Jakim287, have you followed the installation guide on the README ?

The dictionaries generated by this script must be manually installed, in case you wish to use the installation Wizard, please be sure to delete the `frequency.json` and `conjugations.json` from the `.zip` file before trying to install it through the Wizard.

Note that when installing the dictionary through the `.zip` I recommend you install the `frequency.json` and `conjugation.json` through the Wizard before installing the `.zip` file.

> If you install the dictionary before the frequency file you will need to remove the dictionary and reimport it for the frequency to be applied. 

About the sqlite file, that will be loaded correctly after you import the dictionaries, be it using the Wizard, or the manual installation process.

For further reference the installation process mentioned here is based on the [Migaku Dictionary Documentation](https://www.migaku.io/tools-guides/migaku-dictionary/manual#installing-dictionaries).

## Installation

After generating your `<dictionary>.zip` file you must extract it on your Migaku Dictionary `user_files` language folder, if installed correctly you should have this structure:

- `user_files/dictionaries/header.csv` (optional)
- `user_files/dictionaries/<language>/frequency.json`
- `user_files/dictionaries/<language>/conjugations.json`
- `user_files/dictionaries/<language>/<dictionary>/dictionary.json`

Replace `<language>` by your desired language like "English", "German", "Arabic", etc.  
Replace `<dictionary>` by your dictionary name for example `migaku_wr_dict_enar`

If you install the dictionary before the frequency file you will need to remove the dictionary and reimport it for the frequency to be applied.  
The conjugation file might need to be installed using the "Install Conjugation Data From File" option on Migaku Dictionary Settings.

**Comment by guicaulada** [comment]
Hello, it's been over 7 days waiting for a reply, I will close this issue for now, if you have any other issues let me know and I will reopen.
