### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by ghost** [Sighmir/migaku-wr-dict#2]
Hello. I have no knowledge about using such things. I can use only exe programs (lol). Can you instruct me how to use it from scratch? I would be SOOOO grateful. Cheers :)

**Comment by ghost** [comment]
Nevermind, I managed to do it. However 891 words could not be generated. I want to generate these terms separately using this command: npx migaku-wr-dict -f en -t ar -g rainbow.

How to do it so more words are used than just rainbow?

**Comment by guicaulada** [comment]
Hey  mateuszschmidt, glad you figured it out!

With this command you can get the JSON data for any word, just replace the word after the `-g` for the word you want:
- `npx migaku-wr-dict -f en -t ar -g anything`

This could be use to test results for an specific word.

However I think this is not what you want, if you want to try and generate another dictionary with only the 891 words that weren't generated I recommend you copy them on a `.txt` file one word by line and save it somewhere like `words.txt` and use:
- `npx migaku-wr-dict -f en -t ar -w words.txt`

Let me know how it goes for you.

**Comment by ghost** [comment]
Unfortunately I get this message "Request failed with status code 400". 

The next thing I wanted to ask about is that when viewing created dictionary in Migaku addon the results are doubled. For example there is entry of a word "dog" one with a pronunciation and one without it.

**Comment by guicaulada** [comment]
Request failed with status code 400 could indicate the word doesn't exist on the dictionary.

The translations and entries are created based on the WordReference dictionary, if there's a duplicated entry that's probably also present on the WordReference dictionary, what is the exact command you are using ?

If you tell me your `-f` and `-t` and the word that is failing I can look it up on WordReference and explain why it gave you an error 400 and explain the duplicates for the word "dog".

**Comment by ghost** [comment]
I used this to create the dictionary: npx migaku-wr-dict -f en -t pl -n 100000

-f english -t polish

There are no duplicates of this word on Word Reference.

I get this message "Request failed with status code 400" when I just try to test this "npx migaku-wr-dict -f en -t ar -w words.txt" with two words e.g. water and dog. I get results for water, but do not get any results for dog. 

Thank you for your time, I really appreciate it :)

**Comment by guicaulada** [comment]
That's weird, water and dog works just fine for me. For dog I also get no duplicates without definition, there are duplicates, but their definitions extracted from WordReference are present:
```
[{"term":"dog","altterm":"","pronunciation":"/ˈdɒg/","definition":"pies \n\nShe got a dog for Christmas.\nDostała psa na Boże Narodzenie.","pos":"n","examples":"She got a dog for Christmas.\nDostała psa na Boże Narodzenie.","audio":"https://www.wordreference.com/audio/en/us/us/en026602.mp3"},

{"term":"dog","altterm":"","pronunciation":"/ˈdɒg/","definition":"pies \n\nThere are many different breeds of dog.\nIstnieje wiele ras psów.","pos":"n","examples":"There are many different breeds of dog.\nIstnieje wiele ras psów.","audio":"https://www.wordreference.com/audio/en/us/us/en026602.mp3"},

{"term":"dog","altterm":"","pronunciation":"/ˈdɒg/","definition":"psowate \n\nWolves, coyotes and dingoes are all dogs.\nWilki, kojoty i psy dingo należą do rodziny psowatych.","pos":"n","examples":"Wolves, coyotes and dingoes are all dogs.\nWilki, kojoty i psy dingo należą do rodziny psowatych.","audio":"https://www.wordreference.com/audio/en/us/us/en026602.mp3"},

{"term":"dog","altterm":"","pronunciation":"/ˈdɒg/","definition":"pies \n\nI'll get you back for that, you dog!","pos":"n","examples":"I'll get you back for that, you dog!","audio":"https://www.wordreference.com/audio/en/us/us/en026602.mp3"},

{"term":"dog","altterm":"","pronunciation":"/ˈdɒg/","definition":"kumpel \n\nSo how are you doing, you old dog!","pos":"n","examples":"So how are you doing, you old dog!","audio":"https://www.wordreference.com/audio/en/us/us/en026602.mp3"},

{"term":"dog","altterm":"","pronunciation":"/ˈdɒg/","definition":"pokraka \n\nI wouldn't go out with her. She's a dog!","pos":"n","examples":"I wouldn't go out with her. She's a dog!","audio":"https://www.wordreference.com/audio/en/us/us/en026602.mp3"},

{"term":"dog","altterm":"","pronunciation":"/ˈdɒg/","definition":"szmelc \n\nThat car of yours is a dog!","pos":"n","examples":"That car of yours is a dog!","audio":"https://www.wordreference.com/audio/en/us/us/en026602.mp3"},

{"term":"dog","altterm":"","pronunciation":"/ˈdɒg/","definition":"klapa \n\nHis latest film was a dog.","pos":"n","examples":"His latest film was a dog.","audio":"https://www.wordreference.com/audio/en/us/us/en026602.mp3"},

{"term":"dog","altterm":"","pronunciation":"/ˈdɒg/","definition":"zapadka \n\nWhen the dog engages, the gear is locked.","pos":"n","examples":"When the dog engages, the gear is locked.","audio":"https://www.wordreference.com/audio/en/us/us/en026602.mp3"}]
```

If those words are just examples I would need the exact words you're having issues with to investigate what is causing the problem, if you want you can attach your words.txt with the 891 that failed so I can investigate the issues.

**Comment by ghost** [comment]
So this is how it looks in my Migaku:

![image](https://user-images.githubusercontent.com/88561760/129240928-4895c8a2-e12d-4c3e-9167-25be80f311e1.png)

Here are the words my dictionary is missing:

https://drive.google.com/file/d/176jIyKzT_5hPXPfpmTni-aiw9e9P2rY_/view?usp=sharing

I tried creating dictionary once again and it missed some words, but these missing words were different than these from the file.

**Comment by guicaulada** [comment]
Haha, thats pretty weird!

I will look into it and troubleshoot for a bit, might have an update for you later on the day or tomorrow.

**Comment by ghost** [comment]
I hope I do not cause any trouble :) If it is not a problem, maybe you could just generate -f en -t pl with 100000 most frequent word for me? Whatever is the most conveniant for you. If you do not have time for such issues than do not bother, I do not want to be troublesome :)

**Comment by guicaulada** [comment]
I am generating one with `npx migaku-wr-dict -f en -t pl -n 100000` to check for issues.
No worries! It's not a big problem but I might only have answers tomorrow due to the time it takes to generate the dictionary.

**Comment by guicaulada** [comment]
So, I just generated an EN-PL dictionary and installed it, I only had one word fail on me, that word didnt exist on WordReference.

For the word "dog" I get these results:
<img src="https://user-images.githubusercontent.com/7741292/129301306-89936b15-33a4-4079-a954-e63ae3ba38e1.png" width=33% height=33%>

It seems to be working normally, try following the installation steps from the README using the attached .zip file.
[migaku_wr_dict_enpl.zip](https://github.com/Sighmir/migaku-wr-dict/files/6979748/migaku_wr_dict_enpl.zip)

The script is very internet dependent so the errors you got might be due to instabillities on your network during the dictionary generation process.

If you have any other issues let me know!

**Comment by ghost** [comment]
Thank you!

So I still get doubled results and on top of that I cannot find any words that have different american and english spelling. I mean pairs like: behavior-behaviour, analyze-analyse.

**Comment by guicaulada** [comment]
That is weird, it seems we got behaviour there, but I also can't find any results when searching for "behaviour", for example:
![image](https://user-images.githubusercontent.com/7741292/129355284-74fd865c-451e-4cb2-96c8-8bb19953e783.png)
The same happens for "analyse", I wonder if this is an issue with Migaku Dictionary, I feel like it should find those entries.

As for the duplicates it seems there were some changes to the website that could be causing this issue, I will have to investigate and update the code.

I should post an update for this soon.

**Comment by ghost** [comment]
Okay. I managed to find behavior. It works when using "Forward" mode in the browser. I was using "Exact" mode. This fixed the issue. There are still a lot of duplicates though.

**Comment by guicaulada** [comment]
Oh yeah, that was the case for me too, had to change it to "Anywhere" to find results searching by "behaviour".

**Comment by guicaulada** [comment]
I believe I fixed the issue with duplicates, I published the update to the command so next time you use it this problem shouldn't happen anymore.

I regenerated the dictionary after the fix, try using this .zip file:
[migaku_wr_dict_enpl.zip](https://github.com/Sighmir/migaku-wr-dict/files/6983299/migaku_wr_dict_enpl.zip)

About the search for words with multiple spellings I recomend using the "Forward" mode or "Anywhere" mode as this is not something I can easily fix without changing the scrapping method and creating multiple entries.

Let me know how it works for you!

**Comment by ghost** [comment]
Great! Works like a charm :) The file is significantly smaller. Are these 100k words despite that? I mean there are no duplicates so that's probably that, but the file seems a few times smaller. If it is because of absence of duplicates, then everything is fine and I think we can close the topic. I really appreciate your help, thank you :)

**Comment by guicaulada** [comment]
Awesome! Yup! Those should be the top 100k most used words in English + a few combinations like "bad behavior" is also scrapped for the word "behavior".

I will close this topic for now, in case you have any other issues feel free to open a new one!
