### ISSUE TITLE
Using greek doesn't work 

### ISSUE THREAD

**Issue by perlop** [Sighmir/migaku-wr-dict#3]
I get error 404. I saw the url it tries to access and It uses "enel" but the right one is "engr".
for example https://www.wordreference.com/enel/anything this is wrong
and this is correct url:
https://www.wordreference.com/engr/anything
The program tries to access the 1st url and always gets error 404 it should use the 2nd one.
I get error 404 when using this command:
npx migaku-wr-dict -f en -t el -n 20

**Comment by guicaulada** [comment]
If the URL it should access is https://www.wordreference.com/engr/anything you should use `npx migaku-wr-dict -f en -t gr -n 20`

**Comment by guicaulada** [comment]
This must be something that changed recently on the website.

**Comment by guicaulada** [comment]
Apparently Greek is the only language that has the reference tag as `el` on the website but uses `gr` on the links.

**Comment by guicaulada** [comment]
Issue was fixed on b8fe245 so Greek accepts `gr` as a code insteal of `el`.

Version 1.1.3 shouldn't have this issue anymore, running `npx migaku-wr-dict -f en -t gr -n 20` should check and download the latest version.
